
   WARN  The database 'application_prod' does not exist on the 'mariadb' connection.  

  Would you like to create it? (yes/no) [yes]
❯ 
   INFO  Preparing database.  

  Creating migration table .............................................................................. 64.68ms DONE

   INFO  Running migrations.  

  0001_01_01_000000_create_users_table ...............................................................................  
  ⇂ create table `users` (`id` bigint unsigned not null auto_increment primary key, `name` varchar(255) not null, `email` varchar(255) not null, `email_verified_at` timestamp null, `password` varchar(255) not null, `remember_token` varchar(100) null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'  
  ⇂ alter table `users` add unique `users_email_unique`(`email`)  
  ⇂ create table `password_reset_tokens` (`email` varchar(255) not null, `token` varchar(255) not null, `created_at` timestamp null, primary key (`email`)) default character set utf8mb4 collate 'utf8mb4_unicode_ci'  
  ⇂ create table `sessions` (`id` varchar(255) not null, `user_id` bigint unsigned null, `ip_address` varchar(45) null, `user_agent` text null, `payload` longtext not null, `last_activity` int not null, primary key (`id`)) default character set utf8mb4 collate 'utf8mb4_unicode_ci'  
  ⇂ alter table `sessions` add index `sessions_user_id_index`(`user_id`)  
  ⇂ alter table `sessions` add index `sessions_last_activity_index`(`last_activity`)  
  0001_01_01_000001_create_cache_table ...............................................................................  
  ⇂ create table `cache` (`key` varchar(255) not null, `value` mediumtext not null, `expiration` int not null, primary key (`key`)) default character set utf8mb4 collate 'utf8mb4_unicode_ci'  
  ⇂ create table `cache_locks` (`key` varchar(255) not null, `owner` varchar(255) not null, `expiration` int not null, primary key (`key`)) default character set utf8mb4 collate 'utf8mb4_unicode_ci'  
  0001_01_01_000002_create_jobs_table ................................................................................  
  ⇂ create table `jobs` (`id` bigint unsigned not null auto_increment primary key, `queue` varchar(255) not null, `payload` longtext not null, `attempts` tinyint unsigned not null, `reserved_at` int unsigned null, `available_at` int unsigned not null, `created_at` int unsigned not null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'  
  ⇂ alter table `jobs` add index `jobs_queue_index`(`queue`)  
  ⇂ create table `job_batches` (`id` varchar(255) not null, `name` varchar(255) not null, `total_jobs` int not null, `pending_jobs` int not null, `failed_jobs` int not null, `failed_job_ids` longtext not null, `options` mediumtext null, `cancelled_at` int null, `created_at` int not null, `finished_at` int null, primary key (`id`)) default character set utf8mb4 collate 'utf8mb4_unicode_ci'  
  ⇂ create table `failed_jobs` (`id` bigint unsigned not null auto_increment primary key, `uuid` varchar(255) not null, `connection` text not null, `queue` text not null, `payload` longtext not null, `exception` longtext not null, `failed_at` timestamp not null default CURRENT_TIMESTAMP) default character set utf8mb4 collate 'utf8mb4_unicode_ci'  
  ⇂ alter table `failed_jobs` add unique `failed_jobs_uuid_unique`(`uuid`)  
  2024_10_19_120736_create_categories_table ..........................................................................  
  ⇂ create table `categories` (`id` bigint unsigned not null auto_increment primary key, `parent_id` int not null, `name` varchar(255) not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'  
  2024_10_19_121419_create_favorites_table ...........................................................................  
  ⇂ create table `favorites` (`id` bigint unsigned not null auto_increment primary key, `user_id` int not null, `listing_id` int not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'  
  2024_10_19_123444_create_listings_table ............................................................................  
  ⇂ create table `listings` (`id` bigint unsigned not null auto_increment primary key, `title` varchar(255) not null, `descriptions` varchar(255) not null, `parameters` varchar(255) not null, `location` varchar(255) not null, `price` int not null, `user_id` int not null, `is_active` tinyint(1) not null, `status` tinyint(1) not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'  
  2024_10_19_124415_create_followings_table ..........................................................................  
  ⇂ create table `followings` (`id` bigint unsigned not null auto_increment primary key, `following_id` int not null, `follower_id` int not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'  
  2024_10_19_124818_create_reports_table .............................................................................  
  ⇂ create table `reports` (`id` bigint unsigned not null auto_increment primary key, `reporter_id` int not null, `reported_id` int not null, `report_category` varchar(255) not null, `text` varchar(255) not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'  
  2024_10_19_125354_create_addresses_table ...........................................................................  
  ⇂ create table `addresses` (`id` bigint unsigned not null auto_increment primary key, `user_id` varchar(255) not null, `country_name` varchar(255) not null, `city_name` varchar(255) not null, `town_name` varchar(255) not null, `district_name` varchar(255) not null, `postal_code` int not null, `address_text` varchar(255) not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'  
  2024_10_19_130001_create_orders_table ..............................................................................  
  ⇂ create table `orders` (`id` bigint unsigned not null auto_increment primary key, `user_id` varchar(255) not null, `listing_id` varchar(255) not null, `total_price` float(53) not null, `status` varchar(255) not null, `address_id` int not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'  
  2024_10_19_130333_create_chatboxes_table ...........................................................................  
  ⇂ create table `chatboxes` (`id` bigint unsigned not null auto_increment primary key, `seller_id` int not null, `buyer_id` int not null, `message_text` varchar(255) not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'  
  2024_11_19_102326_add_profile_picture_to_users_table ...............................................................  
  ⇂ alter table `users` add `profile_picture` varchar(255) not null default '//cdn.arabul.us/images/default.png'  
  2024_11_19_140828_add_slug_to_listings .............................................................................  
  ⇂ alter table `listings` add `slug` varchar(255) not null  
  2024_11_19_155848_add_lat_lng_to_listings_table ....................................................................  

  2024_11_22_144644_add_google_id_to_users_table .....................................................................  

  2024_11_22_203805_create_parameters_table ..........................................................................  
  ⇂ create table `parameters` (`id` bigint unsigned not null auto_increment primary key, `parameter_name` varchar(255) not null, `parameter_value` varchar(255) not null, `category_ids` varchar(255) not null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'  
  2024_11_24_041402_update_parameters_type ...........................................................................  
  ⇂ alter table `listings` modify `parameters` longtext not null  
  2024_11_28_002048_update_parameters_to_json ........................................................................  
  ⇂ alter table `listings` modify `parameters` json not null  
  2024_12_03_010053_create_conversations_table .......................................................................  
  ⇂ create table `conversations` (`id` bigint unsigned not null auto_increment primary key, `user_one_id` bigint unsigned not null, `user_two_id` bigint unsigned not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'  
  ⇂ alter table `conversations` add constraint `conversations_user_one_id_foreign` foreign key (`user_one_id`) references `users` (`id`) on delete cascade  
  ⇂ alter table `conversations` add constraint `conversations_user_two_id_foreign` foreign key (`user_two_id`) references `users` (`id`) on delete cascade  
  2024_12_03_010109_create_messages_table ............................................................................  
  ⇂ create table `messages` (`id` bigint unsigned not null auto_increment primary key, `conversation_id` bigint unsigned not null, `sender_id` bigint unsigned not null, `recipient_id` bigint unsigned not null, `message` text not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'  
  ⇂ alter table `messages` add constraint `messages_conversation_id_foreign` foreign key (`conversation_id`) references `conversations` (`id`) on delete cascade  
  ⇂ alter table `messages` add constraint `messages_sender_id_foreign` foreign key (`sender_id`) references `users` (`id`) on delete cascade  
  ⇂ alter table `messages` add constraint `messages_recipient_id_foreign` foreign key (`recipient_id`) references `users` (`id`) on delete cascade  
  2024_12_03_015430_add_listing_id_to_conversations ..................................................................  
  ⇂ alter table `conversations` add `listing_id` int not null  
  2024_12_19_032208_create_admin_users_table .........................................................................  
  ⇂ create table `admin_users` (`id` bigint unsigned not null auto_increment primary key, `username` varchar(255) not null, `password` varchar(255) not null, `last_ip_address` varchar(255) not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'  

